spring:
  datasource:
    url: jdbc:postgresql://database:5432/thesis
    username: postgres
    password: postgres

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}